services:
  - type: web
    name: html-to-image-service
    runtime: docker
    repo: https://github.com/Bekimoon0043/Html_image.git
    plan: free
    envVars:
      - key: API_KEY
        sync: false                     # Set manually in Render dashboard
    healthCheckPath: /health
